services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    env_file:
      - .env
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:17
    container_name: invest_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: invest
      POSTGRES_DB: invest_friends
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgconf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  jenkins_home:
